name: Scala CI

on:
  push:
    tags: ['*']
    branches: [ develop, preprod, main ]
  pull_request:
    branches: [ develop, preprod, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: lunatech_airport
        ports:
          - 5442:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup database
      run: bash -c "sleep 10 && chmod u+x /database-init/initialize-airports.sh && /database-init/initialize-airports.sh"
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - uses: coursier/cache-action@v6.3
    
    - name: Run tests
      run: sbt test
