name: Scala CI

on:
  push:
    tags: ['*']
    branches: [ develop, preprod, main ]
  pull_request:
    branches: [ develop, preprod, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: lunatech_airport
        ports:
          - 5442:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres-init:
        image: postgres:13
        depends_on:
          postgres:
            condition: service_healthy
        env:
          PGPASSWORD=postgres
          PGHOST=postgres
        volumes:
          - ../../database-init/initialize-airports.sh:/initialize-airports.sh
          - ../../database-init/schema.sql:/schema.sql
          - ../../database-init/airports.csv:/airports.csv
          - ../../database-init/countries.csv:/countries.csv
          - ../../database-init/runways.csv:/runways.csv
        command: bash -c "sleep 10 && chmod u+x /initialize-airports.sh && /initialize-airports.sh"

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - uses: coursier/cache-action@v6.3
    
    - name: Run tests
      run: sbt test
